export const Bookmarks = [
	{
		name: 'New Window',
		icon: 'assets/images/favicons/favicon.ico',
		background: 'hsla(217, 19%, 38%, 1)',
		url: '',
		category: 'General',
		trigger: '/new',
	},
	{
		name: 'GitHub',
		icon: 'assets/images/icons/github.svg',
		background: 'hsla(213, 11%, 16%, 1)',
		url: 'https://github.com',
		category: 'Development',
		trigger: '/gh',
	},
	{
		name: 'Hacker News',
		icon: 'assets/images/icons/ycombinator.svg',
		background: 'hsla(19, 89%, 54%, 1)',
		url: 'https://news.ycombinator.com/',
		category: 'Development',
		trigger: '/hn',
	},
	{
		name: 'Google Mail',
		icon: 'assets/images/icons/gmail.svg',
		background: 'hsla(0, 0%, 95%, 1)',
		url: 'https://www.google.com/mail',
		category: 'Workspace',
		trigger: '/mail',
	},
	{
		name: 'Google Drive',
		icon: 'assets/images/icons/gdrive.svg',
		background: 'hsla(0, 0%, 95%, 1)',
		url: 'https://drive.google.com/drive/my-drive',
		category: 'Workspace',
		trigger: '/drive',
	},
	{
		name: 'Google Maps',
		icon: 'assets/images/icons/gmaps.svg',
		background: 'hsla(0, 0%, 95%, 1)',
		url: 'https://www.google.com/maps',
		category: 'General',
		trigger: '/map',
	},
	{
		name: 'YouTube',
		icon: 'assets/images/icons/youtube.svg',
		background: 'hsla(348, 100%, 50%, 1)',
		url: 'https://www.youtube.com/',
		category: 'Entertainment',
		trigger: '/yt',
	},
];
