export const Bookmarks = [
	{
		name: 'New Window',
		icon: 'assets/favicons/favicon.ico',
		url: '',
		category: 'General',
		command: '/new',
	},
	{
		name: 'Close Window',
		icon: 'assets/icons/close.svg',
		url: '',
		category: 'General',
		command: '/exit',
	},
	{
		name: 'Google Mail',
		icon: 'assets/icons/gmail.svg',
		url: 'https://www.google.com/mail',
		category: 'Workspace',
		command: '/mail',
	},
	{
		name: 'Google Drive',
		icon: 'assets/icons/gdrive.svg',
		url: 'https://drive.google.com/drive/my-drive',
		category: 'Workspace',
		command: '/drive',
	},
	{
		name: 'Google Maps',
		icon: 'assets/icons/gmaps.svg',
		url: 'https://www.google.com/maps',
		category: 'Workspace',
		command: '/maps',
	},
	{
		name: 'GitHub',
		icon: 'assets/icons/github.svg',
		url: 'https://github.com',
		category: 'Development',
		command: '/gh',
	},
	{
		name: 'Hacker News',
		icon: 'assets/icons/ycombinator.svg',
		url: 'https://news.ycombinator.com/',
		category: 'Development',
		command: '/hn',
	},
	{
		name: 'YouTube',
		icon: 'assets/icons/youtube.svg',
		url: 'https://www.youtube.com/',
		category: 'Entertainment',
		command: '/yt',
	},
	{
		name: 'Spotify',
		icon: 'assets/icons/spotify.svg',
		url: 'https://open.spotify.com/',
		category: 'Entertainment',
		command: '/spot',
	},
	{
		name: 'WhatsApp',
		icon: 'assets/icons/whatsapp.svg',
		url: 'https://web.whatsapp.com/',
		category: 'Social',
		command: '/wa',
	},
	{
		name: 'Telegram',
		icon: 'assets/icons/telegram.svg',
		url: 'https://web.telegram.org/',
		category: 'Social',
		command: '/tele',
	},
	{
		name: 'Reddit',
		icon: 'assets/icons/reddit.svg',
		url: 'https://www.reddit.com/',
		category: 'Social',
		command: '/r',
	},
	{
		name: 'Amazon',
		icon: 'assets/icons/amazon.svg',
		url: 'https://www.amazon.com',
		category: 'Commerce',
		command: '/amz',
	},
	{
		name: 'eBay',
		icon: 'assets/icons/ebay.svg',
		url: 'https://www.ebay.com',
		category: 'Commerce',
		command: '/ebay',
	},
];
