export const Bookmarks = [
	{
		name: 'New Window',
		icon: 'assets/favicons/favicon.ico',
		url: '',
		category: 'General',
		trigger: '/new',
	},
	{
		name: 'Close Window',
		icon: 'assets/icons/close.svg',
		url: '',
		category: 'General',
		trigger: '/exit',
	},
	{
		name: 'Google Mail',
		icon: 'assets/icons/gmail.svg',
		url: 'https://www.google.com/mail',
		category: 'Workspace',
		trigger: '/mail',
	},
	{
		name: 'Google Drive',
		icon: 'assets/icons/gdrive.svg',
		url: 'https://drive.google.com/drive/my-drive',
		category: 'Workspace',
		trigger: '/drive',
	},
	{
		name: 'Google Maps',
		icon: 'assets/icons/gmaps.svg',
		url: 'https://www.google.com/maps',
		category: 'Workspace',
		trigger: '/maps',
	},
	{
		name: 'GitHub',
		icon: 'assets/icons/github.svg',
		url: 'https://github.com',
		category: 'Development',
		trigger: '/gh',
	},
	{
		name: 'Hacker News',
		icon: 'assets/icons/ycombinator.svg',
		url: 'https://news.ycombinator.com/',
		category: 'Development',
		trigger: '/hn',
	},
	{
		name: 'YouTube',
		icon: 'assets/icons/youtube.svg',
		url: 'https://www.youtube.com/',
		category: 'Entertainment',
		trigger: '/yt',
	},
	{
		name: 'Spotify',
		icon: 'assets/icons/spotify.svg',
		url: 'https://open.spotify.com/',
		category: 'Entertainment',
		trigger: '/spot',
	},
	{
		name: 'WhatsApp',
		icon: 'assets/icons/whatsapp.svg',
		url: 'https://web.whatsapp.com/',
		category: 'Social',
		trigger: '/wa',
	},
	{
		name: 'Telegram',
		icon: 'assets/icons/telegram.svg',
		url: 'https://web.telegram.org/',
		category: 'Social',
		trigger: '/tele',
	},
	{
		name: 'Reddit',
		icon: 'assets/icons/reddit.svg',
		url: 'https://www.reddit.com/',
		category: 'Social',
		trigger: '/r',
	},
];
